main:
  - name: Tentang
    url: "/tentang"
    weight: 5
  - name: Arsip
    url: "/arsip"
    weight: 10
  - name: Kategori
    url: "/kategori"
    weight: 15
  - name: Cari
    url: "/cari"
    weight: 20